# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 603023dd530834f80380228d44c05a7f1128eb5de88982d970ce6460360a062e9c83aa98301c48158713a7f7fda6608699a43d15cddeaf207b85e2616dc54637

test:
  secret_key_base: eaa26b5372c99e756cb11623fca0f857b0e3f5fb57df9e177c5e72d4727f3e953c983a6d54eb3d5d18a58715ecd7c42a7451d9da7ff2a162a71a425823b98822

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
