# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 91c525d10369d6d77fda1038a5764ec8bca4732c4a4092fec300eb91a776944a6cd23fe36f51833add537623144e08c184b5831891fa2cabc0a92da4293bffca

test:
  secret_key_base: 5ad7fa1dc21c680f9b37aef11be9db217b3f429c3984586d087938ba34ec20b8f6be13961b77e4c1830e4fcda70da8b8438cd1e20b61b88f27585f88c4ff5fc8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
