# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 623d264df47d0df215cc20d12aaab40ef1755f7ad229bd8670d1565490a94944a07b32ba90c0c97bcedeb2fd82cfa247c940d2a3879e766829b90ba7c949ce68

test:
  secret_key_base: 7660c25e74575647eef014f1c001a41bc0b2c5292944c6e5b0ea0b1fe0c4f88c2d59f5ec9c9f10791cd6914ccabe0d71d8ac2e85bf38ba3a4d9216016c0830a4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
