# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6a0782a0d81b1c7fe4f8bf1e0799c707e7f14fda131e5c0c9edbc1bc661c462ee602d4e98b0947118b652342bcf192a15b4fd7c637228ab913c678ef5b31531b

test:
  secret_key_base: e6bd325438dc5155e43c623eaca1a9c235c2db9feb6769c72edd98483cac29af07dab95571de9e7a1758916ca16c5c4c13a2d6dfbbd3177bb6bea8037c2f9dc3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
